### ISSUE TITLE
Begin+2

### ISSUE THREAD

**Issue by pebbe** [rug-compling/alud#11]
https://github.com/rug-compling/alud/blob/966bf28448bf992825c30cb06d4e117908611a98/v2/deplabels-in.go#L146

Bedoel je hier `node.parent.Begin + 2000` ?

De waardes van `Begin`, `End` en `ID` zijn vermenigvuldigd met 1000.

**Comment by gossebouma** [comment]
Inderdaad. Bovendien is het onduidelijk wat de bedoeling was van dit if-statement. Verwijderen heeft geen effect voor Alpino-treebank. Ik heb het aangepast.
