### ISSUE TITLE
alud vs gossebouma/lassy2ud

### ISSUE THREAD

**Issue by a3lem** [rug-compling/alud#12]
Bedankt om dit te maken. Compileren op macOS voor zowel darwin als linux targets verliep feilloos. 👌

Vraagje: hoe vergelijkt dit project met het tweede in de titel? Een paar details die ik kan gebruiken:

- Naar welke versie van UD wordt er geconverteerd?
- Hoe meten jullie de accuraatheid van de conversie?
- Maken jullie gebruik van dezelfde testsuite als lassy2ud?

Al dit om een antwoord te vinden op de vraag: kan ik beter dit of lassy2ud te gebruiken?

Alvast bedankt!

**Comment by gossebouma** [comment]
Conversie is naar UD Version 2
We hebben wel een experiment gedaan met een handmatig gecorrigeerd corpus, maar ik heb de data daarvoor niet direct bij de hand. De meeste verbeteringen in accuraatheid worden gedaan door handmatige controle op lastige constructies.
alud is een implementatie van lassy2ud in go, waarbij we de xquery code uit lassy2ud geintegreerd hebben in de go code. De overstap naar go is nodig omdat we het script ook gebruiken in toepassingen waarbij we de output van een parser automatisch converteren naar UD, in bv webapplicaties, en daar is de go versie efficienter. 
alud wordt actief onderhouden, en lassy2ud niet meer, dus je kunt beter alud gebruiken.

**Comment by a3lem** [comment]
Perfect! Hier kan ik mee verder.

+1 voor de overstap naar Go. Efficiëntie terzijde, ik geniet ervan hoe makkelijk de build toolchain het maakt om te deployen naar verschillende platformen.

Als ik een suggestie mag doen, het lijkt me geen slecht idee om een vertaalde versie van je uitleg toe te voegen aan de README. Daar valt momenteel niet direct uit af te leiden dat er een historische link is met lassy2ud.
