### ISSUE TITLE
[mogelijke bug] Alleen eerste <alpino_ds> element geconverteerd/aanwezig op alud output

### ISSUE THREAD

**Issue by a3lem** [rug-compling/alud#13]
De alud help text geeft onder andere dit voorbeeld: `alud [options] collection.xml ...`. Dat doet me vermoeden dat alud omkan met bestanden die opeenvolgende <alpino_ds> elementen bevatten, zoals de standaard Lassy Groot *.data bestanden.

Wanneer ik zo'n Lassy bestand probeer te converteren zie ik echter dat enkel en alleen de eerste <alpino_ds> element wordt gevonverteerd. Of het is in ieder geval de enige die op de output verschijnt.

Bijvoorbeeld: _LASSY-GROOT/data/WR-P-E-H_part00001.data_ bevat boven de 300k regels. Dat zijn heel wat geparsde zinnen. Ik voer het volgende uit.

```bash
alud LASSY-GROOT/data/WR-P-E-H_part00001.data > out.conllu
```

_out.conllu_ bevat 9 regels – oftewel de tokens van de eerste zin in het input bestand.

Ik heb dit getest op zowel macOS als Linux.

Enig idee wat er fout loopt?

**Comment by pebbe** [comment]
Dit werkt alleen met alud-dact.

    alud-dact LASSY-GROOT/data/WR-P-E-H_part00001.data > out.conllu

**Comment by a3lem** [comment]
Gewoon even voor de zekerheid – vooraleer ik tijd investeer in Berkeley DB XML te proberen installeren – .dact files zijn een binair formaat, niet? Mijn .data-files daarentegen zijn gewoon plain text XML, van het volgende formaat:

```
<?xml version="1.0" encoding="UTF-8"?>
  <alpino_ds version="1.5">
    <node begin=...
  </alpino_ds>
<?xml version="1.0" encoding="UTF-8"?>
  <alpino_ds version="1.5">
  ...
  </alpino_ds>
...
```

Gaat alud-dact daar effectief op werken? Zo niet splits ik ze wel op in kleinere bestanden.

**Comment by a3lem** [comment]
Gewoon om dit af te ronden, en voor andere nieuwsgierigen, hier is het script dat ik uiteindelijk heb gebruikt om adhv alud (niet alud-dact) LASSY Groot te converteren naar CoNNL-U.

https://gist.github.com/lemontheme/19337013ae839f29041336efde1d9ff5#file-lassy2alud-py
